all:
	g++ test1.cpp -O -g -Wall -Wextra -pedantic -ldl -std=c++11
t2:
	g++ test2.cpp -g -Wall -Wextra -pedantic -ldl -std=c++11
st:
	g++ st.cpp -g -Wall -Wextra -pedantic -ldl -std=c++11
min:
	g++ minimal.cpp -g -Wall -Wextra -pedantic -ldl -std=c++11
morse:
	g++ morse.cpp -g -Wall -Wextra -pedantic -ldl -std=c++11
perf:
	g++ performance.cpp -O -g -Wall -Wextra -pedantic -ldl -std=c++11
